name: Build and update an Amazon Machine Image (AMI) using Packer.

on:
  push:
    paths:
      - "ansible/*"
      - "packer_image/*"
      - ".github/workflows/update_packer_ami.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packer_image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::877680973630:role/Packer-role-AMI
        aws-region: eu-central-1 

    - name: Run Packer Build image
      id: build_image
      run: ./build_ami_version.sh > new_version_ami.txt


    - name: Upload Packer Build 
      id: upload
      if: steps.build_image.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Packer Build Image
        path: new_version_ami.txt


    - name: Remove AMI in AWS
      run: python3 remove_aws_ami.py

    - name: Send plan to Packer Image (as file)
      if: steps.build_image.outcome == 'success'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        document: packer_image/new_version_ami.txt
        message: "✅ Packer Image Build Success."

    - name: Send Telegram message
      if: steps.build_image.outcome != 'success'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "❌ Packer Image Build Failed."

